account_id = "0340d648cb394b95228857ffd4c6f1b9"
name = "watchtower-backend"
main = "src/index.js"
compatibility_date = "2026-05-12"

[observability]
enabled = true

[[d1_databases]]
binding = "watchtower_db"
database_name = "watchtower-db"
database_id = "3e5cdd94-da48-46c9-971c-7a302a364c66"

[triggers]
crons = ["59 18 * * *"]